# Generated by Django 4.2 on 2023-09-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('date', models.DateField(auto_now=True)),
                ('author', models.CharField(max_length=50)),
                ('img1', models.ImageField(upload_to='static/blog_images/')),
                ('para1', models.TextField()),
                ('img2', models.ImageField(blank=True, null=True, upload_to='static/blog_images/')),
                ('para2', models.TextField(blank=True, null=True)),
                ('img3', models.ImageField(blank=True, null=True, upload_to='static/blog_images/')),
                ('para3', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
